-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: vendor/mwstake/mediawiki-component-wikicron/db/patch_cron_pk.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__wiki_cron AS
SELECT
  wc_name,
  wc_interval,
  wc_enabled,
  wc_last_run,
  wc_steps,
  wc_timeout,
  wc_manual_interval,
  wc_wiki_id
FROM /*_*/wiki_cron;
DROP TABLE /*_*/wiki_cron;


CREATE TABLE /*_*/wiki_cron (
    wc_name BLOB NOT NULL,
    wc_wiki_id BLOB NOT NULL,
    wc_interval BLOB NOT NULL,
    wc_enabled SMALLINT UNSIGNED NOT NULL,
    wc_last_run BLOB DEFAULT NULL,
    wc_steps CLOB DEFAULT NULL,
    wc_timeout INTEGER NOT NULL,
    wc_manual_interval BLOB DEFAULT NULL,
    PRIMARY KEY(wc_name, wc_wiki_id)
  );
INSERT INTO /*_*/wiki_cron (
    wc_name, wc_interval, wc_enabled,
    wc_last_run, wc_steps, wc_timeout,
    wc_manual_interval, wc_wiki_id
  )
SELECT
  wc_name,
  wc_interval,
  wc_enabled,
  wc_last_run,
  wc_steps,
  wc_timeout,
  wc_manual_interval,
  wc_wiki_id
FROM
  /*_*/__temp__wiki_cron;
DROP TABLE /*_*/__temp__wiki_cron;
