-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: vendor/mwstake/mediawiki-component-wikicron/db/patch_cron_pk.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/wiki_cron
  MODIFY wc_id INT UNSIGNED NOT NULL;
DROP INDEX `primary` ON /*_*/wiki_cron;
ALTER TABLE /*_*/wiki_cron
  CHANGE wc_id wc_id INT UNSIGNED DEFAULT 1 NOT NULL,
  CHANGE wc_wiki_id wc_wiki_id VARBINARY(255) NOT NULL;
ALTER TABLE /*_*/wiki_cron
  ADD PRIMARY KEY (wc_name, wc_wiki_id);
