-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: vendor/mwstake/mediawiki-component-wikicron/db/patch_cron_wiki_id.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE wiki_cron
  ADD wc_wiki_id TEXT DEFAULT NULL;
