-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: vendor/mwstake/mediawiki-component-wikicron/db/patch_cron_pk.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE wiki_cron
  DROP CONSTRAINT wiki_cron_pkey;
ALTER TABLE wiki_cron
  DROP wc_id;
ALTER TABLE wiki_cron
  ALTER wc_wiki_id
SET
  NOT NULL;
ALTER TABLE wiki_cron
  ADD PRIMARY KEY (wc_name, wc_wiki_id);
