-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/wiki-cron.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE wiki_cron (
  wc_id SERIAL NOT NULL,
  wc_name TEXT NOT NULL,
  wc_interval TEXT NOT NULL,
  wc_enabled SMALLINT NOT NULL,
  wc_last_run TIMESTAMPTZ DEFAULT NULL,
  wc_steps TEXT DEFAULT NULL,
  wc_timeout INT NOT NULL,
  wc_manual_interval TEXT DEFAULT NULL,
  PRIMARY KEY(wc_id)
);


CREATE TABLE wiki_cron_history (
  wch_cron TEXT NOT NULL, wch_time TIMESTAMPTZ NOT NULL,
  wch_pid TEXT NOT NULL
);
